version: '3.9'

services:
  app:
#    build: .
    image: pgesieniec/gsmseller:0.0.3-amd64
    container_name: gsmseller
    ports:
      - "40157:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
#      SPRING_PROFILES_ACTIVE: docker
    restart: always
