spring:
  application:
    name: gsm-seller

  datasource:
    url: jdbc:${DATABASE_URL}?sslmode=require

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
server:
  port: ${PORT:8080}

google:
  vision:
    credentials: ${GOOGLE_CLOUD_VISION_CREDENTIALS}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG