spring:
  h2:
    console:
      enabled: true
  application:
    name: gsm-seller
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
openai:
  api-key: ${OPENAI_API_KEY}
  api-base: https://api.openai.com/v1
  model: gpt-4o-mini

